/**
 * One-shot installer: connect → provision → wire AUD → deploy.
 *
 * A human never creates or copies an AUD. This script creates the Access
 * application, reads the AUD it generated, injects it (with the team domain)
 * into a gitignored Wrangler config, and deploys. It is the CLI equivalent of
 * the hosted "Connect with Cloudflare" button.
 *
 * Required env:
 *   CLOUDFLARE_ACCOUNT_ID        target account
 *   INHOUSE_CONTROL_HOST         e.g. sites.example.com (sites at *.<host>)
 *   INHOUSE_ZONE_NAME            e.g. sites.example.com
 *   INHOUSE_ALLOWED_EMAIL | INHOUSE_ALLOWED_DOMAIN   who Access lets in
 * Optional env:
 *   INHOUSE_APP_NAME (default derived from host), INHOUSE_R2_BUCKET,
 *   INHOUSE_TEAM_DOMAIN (reuse an existing Zero Trust team domain),
 *   INHOUSE_CONFIG_OUT (default wrangler.<app>.jsonc),
 *   INHOUSE_ADMIN_EMAILS, INHOUSE_COMPAT_DATE
 */
import { spawn } from 'node:child_process';
import { writeFile } from 'node:fs/promises';
import { resolveToken } from './lib/cf-credentials';
import { cfFactory, ensureAccessApp, ensureR2Bucket, ensureWildcardDns } from './lib/provision';

const accountId = process.env.CLOUDFLARE_ACCOUNT_ID;
const controlHost = process.env.INHOUSE_CONTROL_HOST;
const zoneName = process.env.INHOUSE_ZONE_NAME;
const allowEmail = process.env.INHOUSE_ALLOWED_EMAIL;
const allowDomain = process.env.INHOUSE_ALLOWED_DOMAIN;
if (!accountId || !controlHost || !zoneName || (!allowEmail && !allowDomain)) {
  throw new Error(
    'Required: CLOUDFLARE_ACCOUNT_ID, INHOUSE_CONTROL_HOST, INHOUSE_ZONE_NAME, and INHOUSE_ALLOWED_EMAIL or INHOUSE_ALLOWED_DOMAIN',
  );
}

const appName = (
  process.env.INHOUSE_APP_NAME ||
  controlHost.split('.')[0] ||
  controlHost
).toLowerCase();
const bucket = process.env.INHOUSE_R2_BUCKET || `${appName}-assets`;
const siteWildcard = `*.${controlHost}`;
const configOut = process.env.INHOUSE_CONFIG_OUT || `wrangler.${appName}.jsonc`;
const compatDate = process.env.INHOUSE_COMPAT_DATE || '2026-06-12';
const adminEmails = process.env.INHOUSE_ADMIN_EMAILS || allowEmail || '';

const token = await resolveToken();
const cf = cfFactory(token);

console.log(`[1/4] Ensuring private R2 bucket "${bucket}"…`);
await ensureR2Bucket(cf, accountId, bucket);

console.log(`[2/4] Ensuring Access application "${appName}" (${controlHost} + ${siteWildcard})…`);
const access = await ensureAccessApp(cf, {
  accountId,
  appName,
  controlHost,
  siteWildcard,
  allowEmail,
  allowDomain,
  teamDomainOverride: process.env.INHOUSE_TEAM_DOMAIN,
});

console.log('[3/4] Ensuring wildcard DNS + writing deploy config (AUD injected automatically)…');
await ensureWildcardDns(cf, accountId, zoneName, controlHost);

const config = {
  $schema: 'node_modules/wrangler/config-schema.json',
  name: appName,
  main: 'build/worker.bundled.mjs',
  compatibility_date: compatDate,
  compatibility_flags: ['nodejs_compat'],
  workers_dev: false,
  preview_urls: false,
  observability: { enabled: true },
  build: { command: 'bun run build' },
  routes: [
    { pattern: controlHost, custom_domain: true },
    { pattern: `${siteWildcard}/*`, zone_name: zoneName },
  ],
  vars: {
    TEAM_DOMAIN: `https://${access.teamDomain}`,
    POLICY_AUD: access.policyAud,
    ADMIN_EMAILS: adminEmails,
    CONTROL_HOST: controlHost,
    SITE_DOMAIN: controlHost,
    MAX_SITE_BYTES: '52428800',
    MAX_FILE_BYTES: '10485760',
    MAX_FILES: '500',
  },
  durable_objects: { bindings: [{ name: 'REGISTRY', class_name: 'InhouseRegistry' }] },
  migrations: [{ tag: 'v1', new_sqlite_classes: ['InhouseRegistry'] }],
  r2_buckets: [{ binding: 'ASSETS', bucket_name: bucket }],
};
await writeFile(
  configOut,
  `// Generated by bun run setup. Gitignored: contains account Access config.\n${JSON.stringify(config, null, 2)}\n`,
);

console.log(`[4/4] Deploying "${appName}"…`);
await new Promise<void>((resolve, reject) => {
  const child = spawn('bunx', ['wrangler', 'deploy', '-c', configOut], {
    stdio: 'inherit',
    env: { ...process.env, CLOUDFLARE_API_TOKEN: token, CLOUDFLARE_ACCOUNT_ID: accountId },
  });
  child.on('error', reject);
  child.on('close', (code) =>
    code === 0 ? resolve() : reject(new Error(`wrangler exited ${code}`)),
  );
});

console.log(`\nDone. https://${controlHost} is live behind Cloudflare Access.`);
console.log('You never touched an AUD — it was created and wired automatically.');
