/**
 * One-shot installer: connect → provision → wire AUD → deploy.
 *
 * A human never creates or copies an AUD. This script creates the Access
 * application, reads the generated AUD, injects it into a gitignored Wrangler
 * config, and deploys.
 *
 * Required env:
 *   CLOUDFLARE_ACCOUNT_ID
 *   INHOUSE_CONTROL_HOST                  e.g. sites.example.com
 *   INHOUSE_ALLOWED_EMAIL | INHOUSE_ALLOWED_DOMAIN
 *   INHOUSE_ZONE_NAME                     existing deployment zone
 *     OR
 *   INHOUSE_PARENT_ZONE                   create/delegate CONTROL_HOST as a child zone
 *
 * Optional: INHOUSE_APP_NAME, INHOUSE_R2_BUCKET, INHOUSE_TEAM_DOMAIN,
 * INHOUSE_CONFIG_OUT, INHOUSE_ADMIN_EMAILS, INHOUSE_COMPAT_DATE.
 */
import { spawn } from 'node:child_process';
import { writeFile } from 'node:fs/promises';
import { resolveToken } from './lib/cf-credentials';
import { ensureChildDelegation, ensureChildZone, waitForActiveZone } from './lib/child-zone';
import {
  cfFactory,
  ensureAccessApp,
  ensureR2Bucket,
  ensureWildcardDns,
  resaveAccessApp,
} from './lib/provision';

const accountId = process.env.CLOUDFLARE_ACCOUNT_ID;
const controlHost = process.env.INHOUSE_CONTROL_HOST;
const configuredZone = process.env.INHOUSE_ZONE_NAME;
const parentZone = process.env.INHOUSE_PARENT_ZONE;
const allowEmail = process.env.INHOUSE_ALLOWED_EMAIL;
const allowDomain = process.env.INHOUSE_ALLOWED_DOMAIN;
if (
  !accountId ||
  !controlHost ||
  (!configuredZone && !parentZone) ||
  (!allowEmail && !allowDomain)
) {
  throw new Error(
    'Required: CLOUDFLARE_ACCOUNT_ID, INHOUSE_CONTROL_HOST, INHOUSE_ZONE_NAME or INHOUSE_PARENT_ZONE, and INHOUSE_ALLOWED_EMAIL or INHOUSE_ALLOWED_DOMAIN',
  );
}

const appName = (
  process.env.INHOUSE_APP_NAME ||
  controlHost.split('.')[0] ||
  controlHost
).toLowerCase();
const bucket = process.env.INHOUSE_R2_BUCKET || `${appName}-assets`;
const siteWildcard = `*.${controlHost}`;
const configOut = process.env.INHOUSE_CONFIG_OUT || `wrangler.${appName}.jsonc`;
const compatDate = process.env.INHOUSE_COMPAT_DATE || '2026-06-12';
const adminEmails = process.env.INHOUSE_ADMIN_EMAILS || allowEmail || '';
const token = await resolveToken();
const cf = cfFactory(token);

let deploymentZone = configuredZone || controlHost;
if (parentZone) {
  console.log(`[1/6] Ensuring isolated child zone "${controlHost}"…`);
  const child = await ensureChildZone(cf, accountId, controlHost);
  console.log(`[2/6] Delegating only "${controlHost}" from parent "${parentZone}"…`);
  await ensureChildDelegation(cf, accountId, parentZone, child);
  console.log(`[3/6] Waiting for child zone activation…`);
  await waitForActiveZone(cf, accountId, controlHost);
  deploymentZone = controlHost;
} else {
  console.log(`[1/6] Using existing zone "${deploymentZone}"…`);
}

console.log(`[4/6] Ensuring private R2 bucket "${bucket}"…`);
await ensureR2Bucket(cf, accountId, bucket);

console.log(`[5/6] Ensuring Access application and injecting its generated AUD…`);
let access = await ensureAccessApp(cf, {
  accountId,
  appName,
  controlHost,
  siteWildcard,
  allowEmail,
  allowDomain,
  teamDomainOverride: process.env.INHOUSE_TEAM_DOMAIN,
});
if (parentZone) {
  const resaved = await resaveAccessApp(cf, accountId, access.applicationId);
  access = { ...access, policyAud: resaved.policyAud };
}

await ensureWildcardDns(cf, accountId, deploymentZone, controlHost);
const config = {
  $schema: 'node_modules/wrangler/config-schema.json',
  name: appName,
  main: 'build/worker.bundled.mjs',
  compatibility_date: compatDate,
  compatibility_flags: ['nodejs_compat'],
  workers_dev: false,
  preview_urls: false,
  observability: { enabled: true },
  build: { command: 'bun run build' },
  routes: [
    { pattern: controlHost, custom_domain: true },
    { pattern: `${siteWildcard}/*`, zone_name: deploymentZone },
  ],
  vars: {
    TEAM_DOMAIN: `https://${access.teamDomain}`,
    POLICY_AUD: access.policyAud,
    ADMIN_EMAILS: adminEmails,
    CONTROL_HOST: controlHost,
    SITE_DOMAIN: controlHost,
    MAX_SITE_BYTES: '52428800',
    MAX_FILE_BYTES: '10485760',
    MAX_FILES: '500',
  },
  durable_objects: { bindings: [{ name: 'REGISTRY', class_name: 'InhouseRegistry' }] },
  migrations: [{ tag: 'v1', new_sqlite_classes: ['InhouseRegistry'] }],
  r2_buckets: [{ binding: 'ASSETS', bucket_name: bucket }],
};
await writeFile(
  configOut,
  `// Generated by bun run setup. Gitignored: contains account Access config.\n${JSON.stringify(config, null, 2)}\n`,
);

console.log(`[6/6] Deploying "${appName}" into zone "${deploymentZone}"…`);
await new Promise<void>((resolve, reject) => {
  const child = spawn('bunx', ['wrangler', 'deploy', '-c', configOut], {
    stdio: 'inherit',
    env: { ...process.env, CLOUDFLARE_API_TOKEN: token, CLOUDFLARE_ACCOUNT_ID: accountId },
  });
  child.on('error', reject);
  child.on('close', (code) =>
    code === 0 ? resolve() : reject(new Error(`wrangler exited ${code}`)),
  );
});

console.log(`\nDone. https://${controlHost} is live behind Cloudflare Access.`);
console.log('The Access AUD was created, re-associated, and wired automatically.');
