// @ts-expect-error generated by adapter-cloudflare during `bun run build:kit`
import kit from '../.svelte-kit/cloudflare/_worker.js';
import coreWorker, { type Env, isCoreRequest, runDueSchedules } from './core-backend';

export { UpRegistry } from './registry';
export { SiteDatabase } from './site-database';
export { SiteSecrets } from './site-secrets';

export default {
  fetch(request: Request, env: Env, context: ExecutionContext) {
    // Dispatch control APIs, the session broker, and every wildcard site before
    // SvelteKit checks its own static asset manifest. Uploaded `/icon.svg` and
    // similar paths must always resolve from the site's private deployment.
    if (isCoreRequest(request, env)) return coreWorker.fetch(request, env, context);
    return kit.fetch(request, env, context);
  },
  scheduled(controller: ScheduledController, env: Env, context: ExecutionContext) {
    context.waitUntil(runDueSchedules(env, new Date(controller.scheduledTime)));
  },
};
