// Generated from public/img/optimism/manifest.json.
export const optimismStudies = {
  "generatedAt": "2026-06-18T00:01:29.428Z",
  "shared": "Dreamlike cinematic destination illustration for Cloudflare Agent Experience. Overwhelming scale but welcoming and thrilling. Deep ink foreground opening into luminous horizon blue, atmosphere cyan, cream, and warm signal orange. Soft distance, broad breathable space, matte architectural surfaces, gentle volumetric light, a world that is inhabited and cared for. The operator is approaching, participating, sharing, or returning\u2014not stranded. Every boundary visibly reveals a good destination. No text, no letters, no logos, no watermark, no dystopian checkpoint, no prison, no bunker, no military posture, no abandoned facility, no hostile monolith, no surveillance imagery.",
  "jobs": [
    {
      "slug": "open-company-horizon",
      "title": "The Company Horizon",
      "mechanism": "Up \u00b7 private publishing",
      "model": "lucid",
      "seed": 3101,
      "shift": "The boundary protects a shared place instead of blocking an outsider.",
      "scene": "A small employee carries a cream folder across a vast elevated bridge into an open, inhabited company city above blue clouds. Warm windows, planted terraces, and coworkers are visible beyond a monumental but welcoming orange arch. The bridge continues into the distance.",
      "prompt": "A small employee carries a cream folder across a vast elevated bridge into an open, inhabited company city above blue clouds. Warm windows, planted terraces, and coworkers are visible beyond a monumental but welcoming orange arch. The bridge continues into the distance. Dreamlike cinematic destination illustration for Cloudflare Agent Experience. Overwhelming scale but welcoming and thrilling. Deep ink foreground opening into luminous horizon blue, atmosphere cyan, cream, and warm signal orange. Soft distance, broad breathable space, matte architectural surfaces, gentle volumetric light, a world that is inhabited and cared for. The operator is approaching, participating, sharing, or returning\u2014not stranded. Every boundary visibly reveals a good destination. No text, no letters, no logos, no watermark, no dystopian checkpoint, no prison, no bunker, no military posture, no abandoned facility, no hostile monolith, no surveillance imagery.",
      "file": "/img/optimism/01-open-company-horizon.webp",
      "resolvedModel": "@cf/leonardo/lucid-origin",
      "bytes": 86532,
      "status": "ok",
      "sourceBytes": 543315,
      "width": 1152,
      "height": 768
    },
    {
      "slug": "trace-becomes-garden",
      "title": "The Trace Garden",
      "mechanism": "Unsurf \u00b7 replayable browser proof",
      "model": "phoenix",
      "seed": 3102,
      "shift": "The recorded path becomes something others can follow and cultivate.",
      "scene": "A glowing browser route winds through a terraced sky garden at dawn. Every turn leaves a small orange marker that becomes a flower, lamp, or signpost. Several people follow the same path safely toward an airy pavilion on the horizon.",
      "prompt": "A glowing browser route winds through a terraced sky garden at dawn. Every turn leaves a small orange marker that becomes a flower, lamp, or signpost. Several people follow the same path safely toward an airy pavilion on the horizon. Dreamlike cinematic destination illustration for Cloudflare Agent Experience. Overwhelming scale but welcoming and thrilling. Deep ink foreground opening into luminous horizon blue, atmosphere cyan, cream, and warm signal orange. Soft distance, broad breathable space, matte architectural surfaces, gentle volumetric light, a world that is inhabited and cared for. The operator is approaching, participating, sharing, or returning\u2014not stranded. Every boundary visibly reveals a good destination. No text, no letters, no logos, no watermark, no dystopian checkpoint, no prison, no bunker, no military posture, no abandoned facility, no hostile monolith, no surveillance imagery.",
      "file": "/img/optimism/02-trace-becomes-garden.webp",
      "resolvedModel": "@cf/leonardo/phoenix-1.0",
      "bytes": 81520,
      "status": "ok",
      "sourceBytes": 573117,
      "width": 1152,
      "height": 768
    },
    {
      "slug": "bounded-commons",
      "title": "Bounded Commons",
      "mechanism": "Terrarium \u00b7 isolated child runs",
      "model": "flux2-klein",
      "seed": 3103,
      "shift": "Containment becomes stewardship: separate habitats within one commons.",
      "scene": "A vast sunlit greenhouse commons contains many distinct glass garden rooms. Each room holds one small working agent tending a different living experiment, while open walkways let human stewards inspect every habitat. Hard boundaries, abundant life, shared daylight.",
      "prompt": "A vast sunlit greenhouse commons contains many distinct glass garden rooms. Each room holds one small working agent tending a different living experiment, while open walkways let human stewards inspect every habitat. Hard boundaries, abundant life, shared daylight. Dreamlike cinematic destination illustration for Cloudflare Agent Experience. Overwhelming scale but welcoming and thrilling. Deep ink foreground opening into luminous horizon blue, atmosphere cyan, cream, and warm signal orange. Soft distance, broad breathable space, matte architectural surfaces, gentle volumetric light, a world that is inhabited and cared for. The operator is approaching, participating, sharing, or returning\u2014not stranded. Every boundary visibly reveals a good destination. No text, no letters, no logos, no watermark, no dystopian checkpoint, no prison, no bunker, no military posture, no abandoned facility, no hostile monolith, no surveillance imagery.",
      "file": "/img/optimism/03-bounded-commons.webp",
      "resolvedModel": "@cf/black-forest-labs/flux-2-klein-9b",
      "bytes": 159310,
      "status": "ok",
      "sourceBytes": 760477,
      "width": 1152,
      "height": 768
    },
    {
      "slug": "memory-bridge",
      "title": "The Memory Bridge",
      "mechanism": "Deja \u00b7 repository-scoped handoff",
      "model": "sdxl-base",
      "seed": 3104,
      "shift": "A handoff carries the failed paths so the next person begins farther ahead.",
      "scene": "Two teams meet halfway across a graceful bridge over a blue cloud valley at sunrise. One passes a translucent archive containing visible branching paths, dead ends, decisions, and a bright continuing route. A welcoming research settlement waits on the far side.",
      "prompt": "Two teams meet halfway across a graceful bridge over a blue cloud valley at sunrise. One passes a translucent archive containing visible branching paths, dead ends, decisions, and a bright continuing route. A welcoming research settlement waits on the far side. Dreamlike cinematic destination illustration for Cloudflare Agent Experience. Overwhelming scale but welcoming and thrilling. Deep ink foreground opening into luminous horizon blue, atmosphere cyan, cream, and warm signal orange. Soft distance, broad breathable space, matte architectural surfaces, gentle volumetric light, a world that is inhabited and cared for. The operator is approaching, participating, sharing, or returning\u2014not stranded. Every boundary visibly reveals a good destination. No text, no letters, no logos, no watermark, no dystopian checkpoint, no prison, no bunker, no military posture, no abandoned facility, no hostile monolith, no surveillance imagery.",
      "file": "/img/optimism/04-memory-bridge.webp",
      "resolvedModel": "@cf/stabilityai/stable-diffusion-xl-base-1.0",
      "bytes": 160958,
      "status": "ok",
      "sourceBytes": 1524995,
      "width": 1152,
      "height": 768
    },
    {
      "slug": "proof-opens-plaza",
      "title": "Proof Opens the Plaza",
      "mechanism": "Gateproof \u00b7 executable claims",
      "model": "flux2-klein-4b",
      "seed": 3105,
      "shift": "Proof is an invitation into a public, inspectable space.",
      "scene": "A tiny operator places a plain receipt into a reader and a colossal set of orange panels unfolds like petals, revealing a lively civic plaza filled with workshops, trees, tables, and people exchanging artifacts. The mechanism is visible and celebratory, not ceremonial security.",
      "prompt": "A tiny operator places a plain receipt into a reader and a colossal set of orange panels unfolds like petals, revealing a lively civic plaza filled with workshops, trees, tables, and people exchanging artifacts. The mechanism is visible and celebratory, not ceremonial security. Dreamlike cinematic destination illustration for Cloudflare Agent Experience. Overwhelming scale but welcoming and thrilling. Deep ink foreground opening into luminous horizon blue, atmosphere cyan, cream, and warm signal orange. Soft distance, broad breathable space, matte architectural surfaces, gentle volumetric light, a world that is inhabited and cared for. The operator is approaching, participating, sharing, or returning\u2014not stranded. Every boundary visibly reveals a good destination. No text, no letters, no logos, no watermark, no dystopian checkpoint, no prison, no bunker, no military posture, no abandoned facility, no hostile monolith, no surveillance imagery.",
      "file": "/img/optimism/05-proof-opens-plaza.webp",
      "resolvedModel": "@cf/black-forest-labs/flux-2-klein-4b",
      "bytes": 51210,
      "status": "ok",
      "sourceBytes": 372159,
      "width": 1152,
      "height": 768
    },
    {
      "slug": "room-knows-work",
      "title": "The Room Knows the Work",
      "mechanism": "Glance \u00b7 ambient project activity",
      "model": "lucid",
      "seed": 3106,
      "shift": "Software activity occupies the room as calm weather, not alarms.",
      "scene": "A serene shared studio at blue hour where project activity appears as slow colored light across walls, water, and a suspended translucent orb. People read, make, and talk without staring at dashboards. The room feels alive, calm, and companionable.",
      "prompt": "A serene shared studio at blue hour where project activity appears as slow colored light across walls, water, and a suspended translucent orb. People read, make, and talk without staring at dashboards. The room feels alive, calm, and companionable. Dreamlike cinematic destination illustration for Cloudflare Agent Experience. Overwhelming scale but welcoming and thrilling. Deep ink foreground opening into luminous horizon blue, atmosphere cyan, cream, and warm signal orange. Soft distance, broad breathable space, matte architectural surfaces, gentle volumetric light, a world that is inhabited and cared for. The operator is approaching, participating, sharing, or returning\u2014not stranded. Every boundary visibly reveals a good destination. No text, no letters, no logos, no watermark, no dystopian checkpoint, no prison, no bunker, no military posture, no abandoned facility, no hostile monolith, no surveillance imagery.",
      "file": "/img/optimism/06-room-knows-work.webp",
      "resolvedModel": "@cf/leonardo/lucid-origin",
      "bytes": 50934,
      "status": "ok",
      "sourceBytes": 464839,
      "width": 1152,
      "height": 768
    },
    {
      "slug": "interface-blooms",
      "title": "The Interface Blooms",
      "mechanism": "svelte-edge \u00b7 generated UI",
      "model": "phoenix",
      "seed": 3107,
      "shift": "The interface arrives as help around a task, then leaves room to work.",
      "scene": "A small group gathers around one physical task artifact on an open terrace. Only the needed interface panels assemble around their hands like translucent leaves, controls facing the people who need them. Beyond the terrace is a huge bright horizon and active city.",
      "prompt": "A small group gathers around one physical task artifact on an open terrace. Only the needed interface panels assemble around their hands like translucent leaves, controls facing the people who need them. Beyond the terrace is a huge bright horizon and active city. Dreamlike cinematic destination illustration for Cloudflare Agent Experience. Overwhelming scale but welcoming and thrilling. Deep ink foreground opening into luminous horizon blue, atmosphere cyan, cream, and warm signal orange. Soft distance, broad breathable space, matte architectural surfaces, gentle volumetric light, a world that is inhabited and cared for. The operator is approaching, participating, sharing, or returning\u2014not stranded. Every boundary visibly reveals a good destination. No text, no letters, no logos, no watermark, no dystopian checkpoint, no prison, no bunker, no military posture, no abandoned facility, no hostile monolith, no surveillance imagery.",
      "file": "/img/optimism/07-interface-blooms.webp",
      "resolvedModel": "@cf/leonardo/phoenix-1.0",
      "bytes": 58148,
      "status": "ok",
      "sourceBytes": 501610,
      "width": 1152,
      "height": 768
    },
    {
      "slug": "shared-terminal-harbor",
      "title": "The Shared Terminal Harbor",
      "mechanism": "Tuiport \u00b7 humans and agents over SSH",
      "model": "flux2-klein-4b",
      "seed": 3118,
      "shift": "The terminal becomes a meeting port rather than a dark private tunnel.",
      "scene": "A vast welcoming harbor at sunrise where compact command vessels arrive along protected blue channels and dock at warm orange terminals. Humans and agents work together at open tables under sweeping canopies. The encrypted route is visible as a calm line across the water.",
      "prompt": "A vast welcoming harbor at sunrise where abstract compact command vessels made of simple geometric blocks arrive along protected blue channels and dock at warm orange terminal platforms. Humans and agents work together at open tables under sweeping canopies. The encrypted route is a calm line across the water. All surfaces are completely blank, with no signs, no labels, no typography. Dreamlike cinematic destination illustration for Cloudflare Agent Experience. Overwhelming scale but welcoming and thrilling. Deep ink foreground opening into luminous horizon blue, atmosphere cyan, cream, and warm signal orange. Soft distance, broad breathable space, matte architectural surfaces, gentle volumetric light, a world that is inhabited and cared for. The operator is approaching, participating, sharing, or returning\u2014not stranded. Every boundary visibly reveals a good destination. No text, no letters, no logos, no watermark, no dystopian checkpoint, no prison, no bunker, no military posture, no abandoned facility, no hostile monolith, no surveillance imagery.",
      "file": "/img/optimism/08-shared-terminal-harbor.webp",
      "resolvedModel": "@cf/black-forest-labs/flux-2-klein-4b",
      "bytes": 54970,
      "status": "ok",
      "sourceBytes": 392953,
      "width": 1152,
      "height": 768,
      "regeneratedFrom": "dreamshaper text artifact"
    },
    {
      "slug": "visible-hand-homecoming",
      "title": "The Visible Hand",
      "mechanism": "machinectl + Desk \u00b7 physical control",
      "model": "flux2-klein",
      "seed": 3109,
      "shift": "Remote action closes the loop by returning evidence to the room.",
      "scene": "A human hand at a small warm desk sends one orange control signal through a visible bounded path toward a distant machine in a bright workshop. A blue return path carries a receipt and a tiny completed artifact back to the desk. Both places feel inhabited and safe.",
      "prompt": "A human hand at a small warm desk sends one orange control signal through a visible bounded path toward a distant machine in a bright workshop. A blue return path carries a receipt and a tiny completed artifact back to the desk. Both places feel inhabited and safe. Dreamlike cinematic destination illustration for Cloudflare Agent Experience. Overwhelming scale but welcoming and thrilling. Deep ink foreground opening into luminous horizon blue, atmosphere cyan, cream, and warm signal orange. Soft distance, broad breathable space, matte architectural surfaces, gentle volumetric light, a world that is inhabited and cared for. The operator is approaching, participating, sharing, or returning\u2014not stranded. Every boundary visibly reveals a good destination. No text, no letters, no logos, no watermark, no dystopian checkpoint, no prison, no bunker, no military posture, no abandoned facility, no hostile monolith, no surveillance imagery.",
      "file": "/img/optimism/09-visible-hand-homecoming.webp",
      "resolvedModel": "@cf/black-forest-labs/flux-2-klein-9b",
      "bytes": 48704,
      "status": "ok",
      "sourceBytes": 466271,
      "width": 1152,
      "height": 768
    },
    {
      "slug": "receipts-return-home",
      "title": "Bring Back Receipts",
      "mechanism": "Agent Experience \u00b7 inspectable results",
      "model": "lucid",
      "seed": 3110,
      "shift": "The expedition returns to a community with artifacts others can reuse.",
      "scene": "A small expedition crosses a wide bridge home at dawn carrying luminous evidence cards, tools, and samples from an enormous computational landscape behind them. Ahead, a communal archive and workshop glow warmly, with people waiting to receive and reuse what came back.",
      "prompt": "A small expedition crosses a wide bridge home at dawn carrying luminous evidence cards, tools, and samples from an enormous computational landscape behind them. Ahead, a communal archive and workshop glow warmly, with people waiting to receive and reuse what came back. Dreamlike cinematic destination illustration for Cloudflare Agent Experience. Overwhelming scale but welcoming and thrilling. Deep ink foreground opening into luminous horizon blue, atmosphere cyan, cream, and warm signal orange. Soft distance, broad breathable space, matte architectural surfaces, gentle volumetric light, a world that is inhabited and cared for. The operator is approaching, participating, sharing, or returning\u2014not stranded. Every boundary visibly reveals a good destination. No text, no letters, no logos, no watermark, no dystopian checkpoint, no prison, no bunker, no military posture, no abandoned facility, no hostile monolith, no surveillance imagery.",
      "file": "/img/optimism/10-receipts-return-home.webp",
      "resolvedModel": "@cf/leonardo/lucid-origin",
      "bytes": 38142,
      "status": "ok",
      "sourceBytes": 477685,
      "width": 1152,
      "height": 768
    }
  ]
} as const;
